### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by JC0624** [imperial-qore/TranAD#36]
Hi,when I run the "python main.py --model TranAD --dataset SWaT --retrain" I get the error

Traceback (most recent call last):
  File "D:\MyProjects\TranAD-main\main.py", line 335, in <module>
    df = pd.concat([df, result], ignore_index=True)
  File "D:\MyPrograms\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\MyPrograms\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 294, in concat
    op = _Concatenator(
  File "D:\MyPrograms\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

**Comment by shreshthtuli** [comment]
Please rebase to the latest version. This issue has been fixed.
